#! /bin/bash

#
# Marc Groenewegen © 2013
#

#
# A script to remove unwanted symbols from file names
#

echo
echo "This command removes symbols and spaces from file names"
echo "***  For ALL FILES IN THIS DIRECTORY ! ***"
echo "  Type ENTER to continue or ^C to quit"

read dummy

for f in *; do
  # replace symbols by ~ for comparison
  oldname=`echo $f | sed "s/'/~/g"`
  oldname=`echo $oldname | sed "s/,/~/g"`
  oldname=`echo $oldname | sed "s/!/~/g"`
  oldname=`echo $oldname | sed "s/&/~/g"`
  oldname=`echo $oldname | sed "s/@/~/g"`
  oldname=`echo $oldname | sed "s/(/~/g"`
  oldname=`echo $oldname | sed "s/)/~/g"`
  oldname=`echo $oldname | sed "s/ /~/g"`

  # remove those symbols
  newname=`echo $f | sed "s/'//g"`
  newname=`echo $newname | sed "s/,//g"`
  newname=`echo $newname | sed "s/!//g"`
  newname=`echo $newname | sed "s/&//g"`
  newname=`echo $newname | sed "s/@//g"`
  newname=`echo $newname | sed "s/(//g"`
  newname=`echo $newname | sed "s/)//g"`
  newname=`echo $newname | sed "s/ //g"`

  if [ $oldname != $newname ] # apparent need for change
  then
    echo mv $f $newname
    mv "$f" $newname
  fi
done

