#! /bin/bash

#
# Marc Groenewegen © 2013
#

#
# A script to remove unwanted symbols from file names
#

echo
echo "This command removes symbols from file names"
echo "Please run spaces2underscores.sh first!"
echo "***  For ALL FILES IN THIS DIRECTORY ! ***"
echo "  Type ENTER to continue or ^C to quit"

read dummy

for f in *; do
  # replace symbols by ~ for comparison
  oldname=`echo $f | sed "s/'/~/g"`
  oldname=`echo $oldname | sed "s/,/~/g"`
  oldname=`echo $oldname | sed "s/!/~/g"`
  oldname=`echo $oldname | sed "s/&/~/g"`
  oldname=`echo $oldname | sed "s/@/~/g"`
  oldname=`echo $oldname | sed "s/(/~/g"`
  oldname=`echo $oldname | sed "s/)/~/g"`
  oldname=`echo $oldname | sed "s/\[/~/g"`
  oldname=`echo $oldname | sed "s/\]/~/g"`
  oldname=`echo $oldname | sed "s/ /~/g"`
  oldname=`echo $oldname | sed "s/:/~/g"`
  oldname=`echo $oldname | sed "s/ -/~/g"`
  oldname=`echo $oldname | sed "s/- /~/g"`
  oldname=`echo $oldname | sed "s/_-_/~/g"`
  oldname=`echo $oldname | sed "s/__/~/g"`
  oldname=`echo $oldname | sed "s/_\./~/g"`
  oldname=`echo $oldname | sed "s/\._/~/g"`

  # remove/replace those symbols
  newname=`echo $f | sed "s/'//g"`
  newname=`echo $newname | sed "s/,//g"`
  newname=`echo $newname | sed "s/!//g"`
  newname=`echo $newname | sed "s/&//g"`
  newname=`echo $newname | sed "s/@//g"`
  newname=`echo $newname | sed "s/(//g"`
  newname=`echo $newname | sed "s/)//g"`
  newname=`echo $newname | sed "s/\[//g"`
  newname=`echo $newname | sed "s/\]//g"`
  newname=`echo $newname | sed "s/:/./g"`
  newname=`echo $newname | sed "s/ -/-/g"`
  newname=`echo $newname | sed "s/- /-/g"`
  newname=`echo $newname | sed "s/_-_/-/g"`
  newname=`echo $newname | sed "s/__/-/g"`
  newname=`echo $newname | sed "s/_\./-/g"`
  newname=`echo $newname | sed "s/\._/-/g"`

  if [ $oldname != $newname ] # apparent need for change
  then
    echo mv $f $newname
    mv "$f" $newname
  fi
done

