#! /bin/bash

#
# Marc Groenewegen © 2015
#


if [ $# -lt 1 ]; then
  echo "Write EDL markers for video file"
  echo "Usage: $0 videofile"
  echo "The name of the edl file is videofile.edl"
  echo
  echo "While playing, set markers with 'i' key"
  exit
fi


INFILE=$1
EXTENSION="${INFILE##*.}"
FILEBASENAME=`basename $INFILE .${EXTENSION}`
EDL_FILE=${FILEBASENAME}.edl

${HOME}/software/mplayer-checkout-2016-01-31/mplayer -ao $AUDIO_DEV -edlout $EDL_FILE $INFILE

