#! /bin/bash

#
# Marc Groenewegen (c) 2011
#

if [ $# -eq 1 ] # convert the specified file only
then
  avconv -i $1 -acodec copy -vn `basename $1 .flv`.aac
  exit
fi


TARGETDIR=stripped_flvs

if [ -d $TARGETDIR ] ; then
  echo "$TARGETDIR directory exists"
else
  echo "creating $TARGETDIR directory"
  mkdir $TARGETDIR
fi

for f in *.flv; do
  avconv -i $f -acodec copy -vn ${TARGETDIR}/`basename $f .flv`.aac
done

