#! /bin/sh

#
# Marc Groenewegen © 2004
#


if [ $# -lt 1 ]; then
  echo "make_index: make html index file"
  echo
  echo "usage: make_index <title> [ > file.html]"
  echo "arguments: Title string"
  echo
  exit
fi


echo "<html>"
echo "<head>"
echo "<style type='text/css'>"
echo "body {background-color: white; font-family: Helvetica,sans-serif;\
font-size: 14px; background: white; color: black;}"
echo "h1 {font-size: 3em; font-weight: normal; color: #c3c3c3;\
letter-spacing: .01em; margin: 0 .05em 0 0; text-align: center; }"
echo "img {border: 1px solid #d0d0d0;}"
echo "</style>"
echo "<title>$1</title>"
echo "</head>"
echo "<body>"
echo "<center>"
echo "<h1>$1</h1>"

for f in *.jpg ; do
 echo "<a href='$f'><img hspace='50' src='thumbnails/$f'></a>"
done

echo "<!--"
echo "<a href='zaal100_20dec2013.zip'>Download zip</a>"
echo "-->"

echo "</center>"
echo "</body>"
echo "</html>"
