#! /bin/bash

#
# Marc Groenewegen, © 2013
#

if [ $# -lt 1 ]; then
  echo "Converts numbers to other units"
  echo
  echo "Supported conversions:"
  echo "to_inches <centimeters>"
  echo "to_cm <inches>"
  echo "to_celcius <fahrenheit>"
  echo "to_fahrenheit <celcius>"
  echo "to_db <ratio>"
  echo "db_to_amp <ratio>"
  exit
fi

case `basename $0` in
  "to_inches")
    CONVERSION="$1/2.54"
  ;;
  "to_cm")
    CONVERSION="$1*2.54"
  ;;
  "to_celcius")
    CONVERSION="($1-32)*5/9"
  ;;
  "to_fahrenheit")
    CONVERSION="$1*9/5+32"
  ;;
  "to_db")
    CONVERSION="10*l($1)/l(10)" # 10*log(x)
    # as we only have natural log we need to express 10log
    #  as follows: 10log(x) = ln(x) / ln(10)
  ;;
  "db_to_amp")
    CONVERSION="e(($1/10)*l(10))" # 10^(x/10)
    # as we only have natural power we need to express 10^x with e^y
    #   as follows: 10^x = e^(x * ln(10) )
  ;;
esac

bc -l << EOF
scale=4
${CONVERSION}
quit
EOF

