#! /bin/bash

#
# Marc Groenewegen (c) 2011
#

if [ $# -eq 1 ] # convert the specified file only
then
  ffmpeg -i $1 -acodec copy -vn `basename $1 .mp4`.aac
  exit
fi


TARGETDIR=stripped_mp4s

if [ -d $TARGETDIR ] ; then
  echo "$TARGETDIR directory exists"
else
  echo "creating $TARGETDIR directory"
  mkdir $TARGETDIR
fi

for f in *.mp4; do
  # ffmpeg -i $f -acodec copy -vn ${TARGETDIR}/`basename $f .mp4`.aac
  ffmpeg -i $f -acodec copy -vn ${TARGETDIR}/$(basename $f .mp4).aac
done

