#! /bin/bash

#
# Marc Groenewegen © 2015
#


if [ $# -lt 2 ]; then
  echo "$0 <file> [scale]"
  echo
  exit
fi

if [ $# -gt 1 ]; then
  SCALE=$2
  FILTER="-filter:v scale=""iw*${SCALE}:ih*${SCALE}"""
fi

# scaling probably works with ffmpeg as well...
ffmpeg -i $1 $FILTER `basename $1 .mp4`_scaled.mp4

