#! /bin/bash

#
# Marc Groenewegen © 2012
#

BASENAME=vbd
NROFPAGES=2

echo "Paste the output into a terminal to execute"

echo gs -sDEVICE=pdfwrite -q -dNOPAUSE -dBATCH -dSAFER \
   -sOutputFile=merged.pdf "\\"

for filenumber in `seq 1 $NROFPAGES`;
do
  numberstring=`printf %01d $filenumber`
  echo -n "$BASENAME${numberstring}.pdf "
done

# gs -sDEVICE=pdfwrite -q -dNOPAUSE -dBATCH -dSAFER
#    -sOutputFile=merged.pdf <file1.pdf> <file2.pdf> ... <file n.pdf>

echo

