#! /bin/bash

#
# Marc Groenewegen © 2012
#

INFILE=$1
NROFSOURCEPAGES=672
#NROFSOURCEPAGES=24
OFFSET=1
PAGE=1
STEP=8

for i in `seq $OFFSET $STEP $NROFSOURCEPAGES`;
do
  echo "Processing source page $i"
  LASTPAGE=$(( i + STEP - 1 ))

  gs -sDEVICE=pdfwrite \
   -q -dNOPAUSE -dBATCH \
   -sOutputFile=pages/page${PAGE}.pdf \
   -dFirstPage=${i} \
   -dLastPage=${LASTPAGE} \
   $INFILE

  PAGE=$(( PAGE + 1 ))

done

