#! /bin/sh

#
# Marc Groenewegen © 2007
#


if [ $# -lt 1 ]; then
  echo "pictcrop: crop png to top left corner x,y and width*height"
  echo
  echo "usage: pictcrop x y w h"
  echo
  exit
fi


new_x=$1
new_y=$2
new_w=$3
new_h=$4


if [ -d converted ] ; then
  echo "converted directory exists"
else
  echo "creating converted directory"
  mkdir converted
fi



for f in *.png; do
  echo converting $f
  convert -crop ${new_w}x${new_h}+${new_x}+${new_y} $f converted/$f
done

