#! /bin/bash

#
# Marc Groenewegen (c) 2011
#

TARGETDIR=stripped_webm

if [ -d $TARGETDIR ] ; then
  echo "$TARGETDIR directory exists"
else
  echo "creating $TARGETDIR directory"
  mkdir $TARGETDIR
fi

for f in *.webm; do
  ffmpeg -i $f -acodec copy -vn ${TARGETDIR}/`basename $f .webm`.ogg
done


