#! /bin/bash

#
# Marc Groenewegen (c) 2011
#

if [ $# -eq 1 ] # convert the specified file only
then
  ffmpeg -i $1 -acodec copy -vn `basename $1 .webm`.ogg
  exit
fi


TARGETDIR=stripped_webm

if [ -d $TARGETDIR ] ; then
  echo "$TARGETDIR directory exists"
else
  echo "creating $TARGETDIR directory"
  mkdir $TARGETDIR
fi

for f in *.webm; do
  ffmpeg -i $f -acodec copy -vn ${TARGETDIR}/`basename $f .webm`.ogg
done


