#! /bin/sh
#

#
# Marc Groenewegen © 2004
#

#xterm -title "$*" -n $1 -fg black -bg white -fn 7x14 -geometry 80x50 -e man $* &
xterm -title "$*" -n $1 -fg black -bg white -fa 'Monospace' -fs 12 -geometry 80x50 -e man $* &

